language: cpp

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - clang-3.5

matrix:
  include:
     # Linux
     - os: linux
       compiler: clang
       env: NODE_VERSION="0.12.2" # node abi 14
     - os: linux
       compiler: clang
       env: NODE_VERSION="0.10.38" # node abi 11
     # OS X
     - os: osx
       compiler: clang
       env: NODE_VERSION="0.12.2" # node abi 14
     - os: osx
       compiler: clang
       env: NODE_VERSION="0.10.38" # node abi 11


before_install:
  - if [[ $(uname -s) == 'Linux' ]]; then
      export CXX="clang++-3.5";
      export CC="clang-3.5";
    fi;
  - rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

install:
  - npm install --build-from-source --clang=1

script:
  - npm test

after_success:
  - ./test/travis-publish.sh
